name: Deploy Medusa to AWS ECS

on:
  push:
    branches:
      - main  # This triggers the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu VM

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # This checks out the code from your GitHub repository

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # Sets up Terraform CLI in the runner

    - name: Terraform Init
      run: terraform init  # Initialize Terraform configuration
      working-directory: ./  # Ensure you are in the correct directory

    - name: Terraform Plan
      run: terraform plan  # Plan the Terraform changes
      working-directory: ./  # Run from the root directory

    - name: Terraform Apply
      run: terraform apply --auto-approve  # Apply Terraform changes automatically
      working-directory: ./  # Run from the root directory
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use AWS secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use AWS secrets
